---
title: "MAP_02_Auditorne"
author: "Damir Pintar"
date: "09/03/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(fBasics)
library(ggplot2)
library(GGally)
library(gridExtra)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
```

## 3.8

```{r}
a <- matrix(c(1, 2, 2, -2), ncol = 2)
eigen(a)

```

```{r}
eig <- eigen(a)
eig$values[1] * eig$vectors[, 1] %*% t(eig$vectors[, 1]) + eig$values[2] * eig$vectors[, 2] %*% t(eig$vectors[, 2])

```



## 3.9

```{r}
a.inv <- solve(a)
a.inv
```

```{r}
eigen(a.inv)
```


## 3.10

```{r}
a <- matrix(c(4, 4.001, 4.001, 4.002), ncol = 2)
b <- a
b[2,2] <- b[2,2] + 0.000001
a
b

```



```{r}
solve(a)
```



```{r}
solve(b)
```



## 3.24

```{r}
covMat <- matrix(c(4, 0, 0, 0, 9, 0, 0, 0, 1), ncol = 3)
covMat
solve(covMat)
```

```{r}
eigen(covMat)
```

```{r}
eigen(solve(covMat))
```



## 3.25

```{r}
covMat <- matrix(c(25, -2, 4, -2, 4, 1, 4, 1, 9), ncol = 3)
covMat
```

```{r}
V.pol <- (diag(covMat) * diag(3)) %>% sqrt
V.pol
```

```{r}
ro <- solve(V.pol) %*% covMat %*% solve(V.pol)
ro
```


```{r}
V.pol %*% ro %*% V.pol
```











